# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "tomcat" do |tomcat|
    tomcat.vm.box = "jacobw/fedora35-arm64"
    tomcat.vm.network "private_network", ip: "192.168.56.10"
    tomcat.vm.network "public_network"
    tomcat.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.memory = "1024"
    end
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "spox/ubuntu-arm"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.21"
    web01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
    end
  end

end

